/*
 * Информация о пользователе
 *
 * API для получения баланса кошелька пользователя, истории операций и инфорации об авторизованном пользователе **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**
 *
 * API version: 1
 * Contact: supportautoload@avito.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package user

import "strconv"

type UserInfoSelf struct {
	// Email пользователя
	Email string `json:"email,omitempty"`
	// Идентификатор пользователя
	Id int32 `json:"id,omitempty"`
	// Имя пользователя
	Name string `json:"name,omitempty"`
	// Телефон пользователя по умолчанию. При отсутствии подтвержденного телефона вернется пустая строка
	Phone string `json:"phone,omitempty"`
	// Ссылка на профиль пользователя
	ProfileUrl string `json:"profile_url,omitempty"`
}

func (u UserInfoSelf) String() string {
	return strconv.Itoa(int(u.Id)) + " " + u.Name + " " + u.Phone + " " + u.ProfileUrl + " " + u.Email
}
