openapi: 3.0.0
info:
  title: Мессенджер
  description: |
    API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны

    **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**
  contact:
    email: supportautoload@avito.ru
  version: "1"
servers:
- url: https://api.avito.ru/
tags:
- name: Messenger
  description: |
    # API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны
    Описание API произведено в формате [**Swagger 3.0**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md).
    Вы можете использовать данный файл для ознакомления с методами API, а также для генерации базового кода для работы с API на удобном для вас языке программирования с помощью утилиты
    [**Swagger Codegen**](https://swagger.io/swagger-codegen/) или online сервиса [**Swagger Editor**](https://editor.swagger.io/).

    **Авито API для бизнеса предоставляется согласно [Условиям использования](https://api.avito.ru/docs/public/APITermsOfServiceV1.pdf).**
    По всем вопросам работы с API необходимо обращаться в Службу Поддержки профессиональных инструментов:

    <li>телефон: <b>+7 495 777-10-66</b></li>
    <li>email: <a href="mailto:supportautoload@avito.ru">supportautoload@avito.ru</a></li>

    # Типы авторизации
    Для использования данного API запрос должен быть авторизован. В данный момент API Авито использует следующие механизмы авторизации. <!-- ReDoc-Inject: <security-definitions> -->
  x-displayName: Мессенджер
paths:
  /messenger/v1/accounts/{user_id}/blacklist:
    post:
      tags:
      - Messenger
      summary: Добавление пользователя в blacklist
      description: |
        Добавление пользователя в blacklist
      operationId: postBlacklist
      security:
      - AuthorizationCode:
        - messenger:write
      - ClientCredentials: []
  /messenger/v1/accounts/{user_id}/chats:
    get:
      tags:
      - Messenger
      summary: Получение информации по чатам
      description: |
        Возвращает список чатов
      operationId: getChats
      security:
      - AuthorizationCode:
        - messenger:read
      - ClientCredentials: []
  /messenger/v1/accounts/{user_id}/chats/{chat_id}:
    get:
      tags:
      - Messenger
      summary: Получение информации по чату
      description: |
        Возвращает данные чата и последнее сообщение в нем
      operationId: getChatById
      security:
      - AuthorizationCode:
        - messenger:read
      - ClientCredentials: []
  /messenger/v1/accounts/{user_id}/chats/{chat_id}/messages:
    post:
      tags:
      - Messenger
      summary: Отправление сообщения
      description: |
        На данный момент можно отправить только текстовое сообщение
      operationId: postSendMessage
      security:
      - AuthorizationCode:
        - messenger:write
      - ClientCredentials: []
  /messenger/v1/accounts/{user_id}/chats/{chat_id}/messages/:
    get:
      tags:
      - Messenger
      summary: Получение списка сообщений
      description: |
        Получение списка сообщений, используйте только для изначальной загрузки сообщений на экране, для получения новых сообщений в реальном времени используйте webhooks
      operationId: getMessages
      security:
      - AuthorizationCode:
        - messenger:read
      - ClientCredentials: []
  /messenger/v1/accounts/{user_id}/chats/{chat_id}/messages/{message_id}:
    post:
      tags:
      - Messenger
      summary: Удаление сообщения
      description: |
        Сообщение не пропадает из истории, а меняет свой тип на deleted.
        Удалять можно только те сообщения которые не старше часа с момента их создания.
      operationId: deleteMessage
      security:
      - AuthorizationCode:
        - messenger:write
      - ClientCredentials: []
  /messenger/v1/accounts/{user_id}/chats/{chat_id}/read:
    post:
      tags:
      - Messenger
      summary: Прочитать чат
      description: |
        После успешного получения списка сообщений необходимо вызвать этот метод для того, чтобы чат стал прочитанным.
      operationId: chatRead
      security:
      - AuthorizationCode:
        - messenger:read
      - ClientCredentials: []
  /messenger/v1/webhook:
    post:
      tags:
      - Messenger
      summary: Включение уведомлений (webhooks)
      description: |
        Включение уведомлений
      operationId: postWebhook
      security:
      - AuthorizationCode:
        - messenger:read
      - ClientCredentials: []
  /messenger/v1/webhook/unsubscribe:
    post:
      tags:
      - Messenger
      summary: Отключение уведомлений (webhooks)
      description: |
        Отключение уведомлений
      operationId: postWebhookUnsubscribe
      security:
      - AuthorizationCode:
        - messenger:read
      - ClientCredentials: []
  /messenger/v2/accounts/{user_id}/chats/{chat_id}/messages/:
    get:
      tags:
      - Messenger
      summary: Получение списка сообщений V2
      description: |
        Получение списка сообщений.  **Не помечает чат прочитанным**
        После успешного списка сообщений необходимо вызвать [метод](https://api.avito.ru/docs/api.html#operation/chatRead), который сделат чат прочитанным.
      operationId: getMessagesV2
      security:
      - AuthorizationCode:
        - messenger:read
      - ClientCredentials: []
  /messenger/v2/webhook:
    post:
      tags:
      - Messenger
      summary: Включение уведомлений V2 (webhooks)
      description: |
        Включение **V2** уведомлений. <LINK_TO_V2_WEBHOOKS>
      operationId: postWebhookV2
      security:
      - AuthorizationCode:
        - messenger:read
      - ClientCredentials: []
components:
  securitySchemes:
    AuthorizationCode:
      type: oauth2
      description: "Это API использует OAuth 2 с механизмом authorization_code. Ис\
        пользуйте его для доступа к данным других пользователей при разработке сто\
        роннего приложения. [Подробнее](/api-catalog/auth/documentation#tag/ApplicationAccess)"
      flows:
        authorizationCode:
          authorizationUrl: https://avito.ru/oauth
          tokenUrl: https://api.avito.ru/token
          scopes:
            autoload:reports: Получение отчетов Автозагрузки
            items:apply_vas: Применение дополнительных услуг
            items:info: Получение информации об объявлениях
            job:cv: Получение информации резюме
            job:negotiations: Получение информации об откликах на вакансии
            job:write: Изменение объявлений вертикали Работа
            messenger:read: Чтение сообщений в мессенджере Авито
            messenger:write: Модифицирование сообщений в мессенджере Авито
            short_term_rent:read: Получение информации об объявлениях краткосрочной
              аренды
            short_term_rent:write: Изменение объявлений краткосрочной аренды
            stats:read: Получение статистики объявлений
            user:read: Получение информации о пользователе
            user_balance:read: Получение баланса пользователя
            user_operations:read: Получение истории операций пользователя
    ClientCredentials:
      type: oauth2
      description: "Это API использует OAuth 2 с механизмом client_credentials. Ис\
        пользуйте его для доступа к возможностям своей личной учетной записи. [Под\
        робнее](#tag/Access)"
      flows:
        clientCredentials:
          tokenUrl: https://api.avito.ru/token
          scopes: {}
